name: subtree-matrix
on:
  push:
    branches:
      - main
      - npm2pnpm
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync-downstream:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        path: [
            #
            next-prisma-starter,
            next-prisma-websockets-starter,
            next-prisma-todomvc,
            next-minimal-starter,
            next-big-router,
            minimal,
            minimal-react,
          ]

    name: Update downstream ${{ matrix.path }} package

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      # Nested workspaces use NPM workspaces but we generate a PNPM lockfile
      # => we convert the workspace to PNPM before generating the lockfile
      - name: Convert to PNPM
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            const examplePath = path.join(process.cwd(), 'examples', '${{ matrix.path }}');
            console.log({ examplePath });
            const packageJson = require(path.join(examplePath, 'package.json'));
            const { workspaces, ...rest } = packageJson;

            if (!workspaces) return;

            const newPkgJson = JSON.stringify({ ...rest }, null, 2);
            fs.writeFileSync(path.join(examplePath, 'package.json'), newPkgJson);

            const pnpmWorkspace = `packages:\n` + workspaces.map((ws) => `  - '${ws}'`).join('\n');
            fs.writeFileSync(path.join(examplePath, 'pnpm-workspace.yaml'), pnpmWorkspace);

      - name: Install dependencies and create separate lockfile
        run: |
          echo "shared-workspace-lockfile=false" >> .npmrc
          echo "link-workspace-packages=false" >> .npmrc
          cp ./pnpm-lock.yaml ./examples/${{ matrix.path }}/pnpm-lock.yaml
          pnpm install --no-frozen-lockfile

      - name: Commit changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "trpc-bot"
          git add .
          git commit -m "chore: sync lockfile"

      - name: Sync downstream
        uses: nxtlvlsoftware/git-subtree-action@1.1
        with:
          repo: 'trpc/examples-${{ matrix.path }}'
          path: 'examples/${{ matrix.path }}'
          deploy_key: ${{ secrets.TRPC_DEPLOY_TOKEN }}
          force: true # will force push to the downstream repository
